export const COUNTRIES: Record<string, { name: string; slug: string }> = {
  us: { name: "United States", slug: "" },
  uk: { name: "United Kingdom", slug: "uk" },
  ca: { name: "Canada", slug: "ca" },
  au: { name: "Australia", slug: "au" },
  fr: { name: "France", slug: "fr" },
  de: { name: "Germany", slug: "de" },
  jp: { name: "Japan", slug: "jp" },
  it: { name: "Italy", slug: "it" },
  es: { name: "Spain", slug: "es" },
  nl: { name: "Netherlands", slug: "nl" },
  se: { name: "Sweden", slug: "se" },
  dk: { name: "Denmark", slug: "dk" },
  no: { name: "Norway", slug: "no" },
  fi: { name: "Finland", slug: "fi" },
  ch: { name: "Switzerland", slug: "ch" },
  at: { name: "Austria", slug: "at" },
  ie: { name: "Ireland", slug: "ie" },
  nz: { name: "New Zealand", slug: "nz" },
  be: { name: "Belgium", slug: "be" },
  sg: { name: "Singapore", slug: "sg" },
  tw: { name: "Taiwan", slug: "tw" },
};
